markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.16.6"
plugins:
- jekyll-feed
- jekyll-include-cache
- jekyll-paginate
- jekyll-analytics
minimal_mistakes_skin: dark
locale: en-US
title: Final Frontier Aerospace Systems and Technology
title_separator: |
subtitle: Rocketry Team at Kansas State University
name: Final Frontier Aerospace Systems and Technology
description: >-
  Description of our website
url: https://ffaero.com
baseurl: /
repository: final-frontier-aerospace/final-frontier-aerospace.github.io
#head_scripts:
#teaser:
#logo:
#masthead_title:
#breadcrumbs:
defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: single
    read_time: true
    author_profile: false
    comments: false
    share: true
    related: true
#words_per_minute:
search: true
paginate: 10
paginate_path: /posts/:num
jekyll_analytics:
  GoogleAnalytics:
    id: UA-146645847-1
