markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
minimal_mistakes_skin: dark
locale: en-US
title: Final Frontier Aerospace Systems and Technology
title_separator: |
subtitle: Rocketry team at Kansas State University
name: Final Frontier Aerospace Systems and Technology
description: >-
  Description of our website
url: https://ffaero.com
baseurl: /
repository: final-frontier-aerospace/final-frontier-aerospace.github.io
#head_scripts:
#teaser:
#logo:
#masthead_title:
#breadcrumbs:
defaults:
- scope:
    path: ""
    type: posts
  values:
    read_time: true
#words_per_minute:
search: true
